[package]
name = "gladius"
version = "0.1.0"
edition = "2021"
authors = [ "Matthew Dickson hi@mattdickson.io" ]

[dependencies]
gladius_core = { path = "../core" }
itertools = "0.11"
rustyline = "12.0"