[package]
name = "gladius_core"
version = "0.1.0"
edition = "2021"
authors = [ "Matthew Dickson hi@mattdickson.io"]

[dependencies]
async-trait = "0.1"
tokio = "1.30"

[dev-dependencies]
indoc = "2.0"