[package]
name = "gladius_core"
version = "0.1.0"
edition = "2021"
authors = [ "Matthew Dickson hi@mattdickson.io"]

[dependencies]
rand = { version = "0.8", features = [ "small_rng" ] }
lazy_static = "1.4"

[dev-dependencies]
indoc = "2.0"
pretty_assertions = "1.4"